#############################
# Xups for Hexo 主题配置文件
# Jelon
# http://jelon.top
#############################

#----------------------------
# 头部导航
#----------------------------
menu:
  home:
    name: 首页
    link: /
    icon: icon-home
  lab:
    name: 实验室
    link: /lab/
    icon: icon-lab
  about:
    name: 关于
    link: /about/
    icon: icon-about
  comment:
    name: 留言
    link: /comment/
    icon: icon-comment

#----------------------------
# 副导航
#----------------------------
subnav:
  github: "#"
  weibo: "#"
  rss: "#"
  zhihu: "#"

#----------------------------
# RSS
#----------------------------
rss: /atom.xml

#----------------------------
# Favicon
#----------------------------
favicon: /favicon.ico

#----------------------------
# 头像url
#----------------------------
avatar: /img/804033.png

#----------------------------
# 全局作者
#----------------------------
author: Zed

#----------------------------
# content 文章描述字数
#----------------------------
content-size: 120

#----------------------------
# 是否开启分享
#----------------------------
share: true

#----------------------------
# 侧栏是否显示微博秀
#----------------------------
weibo_show:
  enable: false
  code: <iframe id="myWeibo" width="100%" height="550" class="share_self"  frameborder="0" scrolling="no" src="http://widget.weibo.com/weiboshow/index.php?language=&width=0&height=550&fansRow=2&ptype=1&speed=0&skin=1&isTitle=0&noborder=0&isWeibo=1&isFans=0&uid=xxxx&verifier=796ea597&dpc=1"></iframe>

#----------------------------
# 是否开启评论
#----------------------------
comment:
  enable: true
  owner: kingzd   #你的 GitHub ID
  repo: repo   #存储评论的 repo
  client_id: f56fec6294e9b3dafbb4 #client ID
  client_secret: d2c7d3358239afe9c108647c36918bb0d7ab2dfa  #client secret

#----------------------------
# 是否开启云标签
#----------------------------
tagcloud: true

#----------------------------
# 友情链接
#----------------------------
friends:
  enable: true
  list:
    1:
      name: 看雪论坛
      title: 技术博客
      link: https://bbs.pediy.com/user-804033.htm
    #2:
    #  name: Haoren博客
    # title: 网络安全博客
    #  link: http://blog.sina.com.cn/u/1825875765

#----------------------------
# 头部链接
#----------------------------
head_links:
  enable: true
  list:
    sup:
      0:
        name: Github
        link: https://github.com/kingzd
    sub:
      sinaweibo:
        name: 看雪论坛
        link: https://bbs.pediy.com/user-804033.htm
#----------------------------
# SEO
#----------------------------
SEO:
  keywords: Zed, 前端, Web, Android,逆向
  description: Zed个人小站

#----------------------------
# 百度分析
#----------------------------
baidu_analytics: true

#----------------------------
# 高亮样式
#----------------------------
highlight_theme: normal
#----------------------------
# CDN
# 如: //7xs305.com1.z0.glb.clouddn.com/
# 主要以下两个目录进行 cdn 存储
#   - img 图片资源下的 thumbnail 目录
#   - css 样式资源下的 fonts 目录
#----------------------------
CDN:
